theme: jekyll-theme-minimal
title: Alma Eguizabal
description: Research Associate and last year PhD student
logo: https://www.xing.com/image/2_8_0_962412c3a_30522263_1/alma-eguizabal-foto.1024x1024.jpg


